<?php

global $rusefi;
global $dialogId;
global $msqs;

include_once("view/view_ts_dialog.php");

ob_start();
?>
<!-- generated by https://loading.io -->
<div id="loading" class="loading-diff"><img src="view/img/loading.gif" /></div>

<script src="view/lib/simplePagination/jquery.simplePagination.js"></script>
<div class="pageSelector"></div>
<script>
$(function() {
	$(".pageSelector").pagination({
		items: <?=$panelsTotalNum;?>,
		itemsOnPage: <?=$panelsNum;?>,
		currentPage: <?=$pageIdx;?>,
		hrefTextPrefix: "<?=$baseUrl;?>&page=",
		cssStyle: 'light-theme',
		onPageClick: function (event, page) {
			$("#loading").show();
			$(".tsDialog").parent().hide();
		}
	});
});
</script>

<div class="ts-dialogs ts-diff" isAutoOpen="true">
<div class="tsDialog" id="dlgDiff" title="Difference Report">
<table class='ts-diff-table' border=0>
<tr><td class='ts-label'><?=$html["header"][0];?></td>
<td class='ts-diff-separator'></td>
<td class='ts-label'><?=$html["header"][1];?></td>
</tr>
<?php

if (count($panels) == 0) {
	echo "<tr><td class='ts-label ts-no-diff' colspan=3><h3>No differences!</h3></td></tr>";
}

foreach ($panels as $mi) {
?>
<tr><td class='ts-label ts-diff-label'>
<?php
	$msqMap = $msqs[0]->msqMap;
	printDialog(0, $msqMap, $msqs[0], $mi, FALSE, FALSE, FALSE);
?>
</td><td class='ts-diff-separator'></td>
<td class='ts-label ts-diff-label'>
<?php
	$msqMap = $msqs[1]->msqMap;
	printDialog(1, $msqMap, $msqs[1], $mi, FALSE, FALSE, FALSE);
?>
</td></tr>
<?php
}
?>
</table>
</div>
</div>

<div class="pageSelector"></div>

<script src="view/ts.js"></script>

<?php

$html["ts"] = ob_get_contents();
ob_end_clean();

?>